# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8038bd1f56b013c3a56f9b057017c18ca86c9dc0f79fb5fd7f4f1a36ae79213583c03aa4a79df6983eb0a3d1f9c5aea50912bbe1a7a96cfdd26f5359663b5c8

test:
  secret_key_base: c8a92f09d93e2890d1f4637c1d5b006d79df7a9a4904b1bc1849b96df419153e86b836ac18235a5fdd34e9a1c678c40922d7c3147d68b2fc86025b46063ec99d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
